- Name : Tanishq Harit
- CWID : 20031876

# System of Linear Equations with a Unique Solution, Matrix Inverse and the Determinant

The goal of this homework is to learn how to solve systems of linear equations and to be able to compute the determinant and the inverse of an invertible matrix.

**After this assignment you will be able to:**
- Use `NumPy` package to set up the arrays corresponding to the system of linear equations.
- Evaluate the determinant of a matrix and find the solution of the system with `NumPy` linear algebra package.
- Perform row reduction to bring matrix into row echelon form
- Find the solution for the system of linear equations using row reduced approach.
- Compute the inverse of a matrix with `Numpy` linear algebra package and using row reduction approach.

## 1. Solving System of Linear Equations

### 1.1 Row Reduction approach

Solve the following system of linear equations using the reduction method (as mentioned in the week 2 lab):
$$\begin{cases}
x + 2y - 3z + 4w = 12, \\ 2x + 2y - 2z + 3w = 10, \\ y + z = -1, \\ x - y + z - 2w = -4 \end{cases}\tag{1}$$


In [1]:
import numpy as np

In [2]:
A = np.array([
        [1, 2, -3, 4],
        [2, 2, -2, 3],
        [0, 1, 1, 0],
        [1, -1, 1, -2]
    ], dtype=np.dtype(float))

b = np.array([12, 10, -1, -4], dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nArray b:")
print(b)

Matrix A:
[[ 1.  2. -3.  4.]
 [ 2.  2. -2.  3.]
 [ 0.  1.  1.  0.]
 [ 1. -1.  1. -2.]]

Array b:
[12. 10. -1. -4.]


In [3]:
# shape() method of numpy
print(f"Shape of A: {np.shape(A)}")
print(f"Shape of b: {np.shape(b)}")

Shape of A: (4, 4)
Shape of b: (4,)


In [4]:
# Making Row Operations Functions
def MultiplyRow(M, row, scalar):
    """Multiplies a row by a scalar."""
    M_new = M.copy()
    M_new[row] = M_new[row] * scalar
    return M_new

def AddRows(M, row_num_1, row_num_2, scalar):
    """Adds scalar times row_num_1 to row_num_2."""
    M_new = M.copy()
    M_new[row_num_2] = scalar * M_new[row_num_1] + M_new[row_num_2]
    return M_new

def ExchangeRows(M, row_num_1, row_num_2):
    """Exchanges row_num_1 and row_num_2."""
    M_new = M.copy()
    M_new[[row_num_1, row_num_2]] = M_new[[row_num_2, row_num_1]]
    return M_new

In [5]:
# Augmented Matrix
A_aug = np.array([
    [1, 2, -3, 4, 12],
    [2, 2, -2, 3, 10],
    [0, 1, 1, 0, -1],
    [1, -1, 1, -2, -4]
], dtype=float)
print("Augmented Matrix:")
print(A_aug)

Augmented Matrix:
[[ 1.  2. -3.  4. 12.]
 [ 2.  2. -2.  3. 10.]
 [ 0.  1.  1.  0. -1.]
 [ 1. -1.  1. -2. -4.]]


In [6]:
# Applying Row Operations Functions
A_aug = AddRows(A_aug, 0, 1, -2)
A_aug = AddRows(A_aug, 0, 3, -1)
A_aug = MultiplyRow(A_aug, 1, 1/A_aug[1,1])
A_aug = AddRows(A_aug, 1, 2, -A_aug[2,1])
A_aug = AddRows(A_aug, 1, 3, -A_aug[3,1])
A_aug = MultiplyRow(A_aug, 2, 1/A_aug[2,2])
A_aug = AddRows(A_aug, 2, 3, -A_aug[3,2])
A_aug = MultiplyRow(A_aug, 3, 1/A_aug[3,3])
print("Row Echelon Form:")
print(A)

Row Echelon Form:
[[ 1.  2. -3.  4.]
 [ 2.  2. -2.  3.]
 [ 0.  1.  1.  0.]
 [ 1. -1.  1. -2.]]


In [7]:
# Back substitution to solve
w = A_aug[3,4]
z = A_aug[2,4] - A_aug[2,3] * w
y = A_aug[1,4] - A_aug[1,2] * z - A_aug[1,3] * w
x = A_aug[0,4] - A_aug[0,1] * y - A_aug[0,2] * z - A_aug[0,3] * w
print("Solution:")
print(f"x = {x}, y = {y}, z = {z}, w = {w}")

Solution:
x = 1.0, y = 0.0, z = -1.0, w = 2.0


### 1.2 `Numpy` linear algebra package
Solve the above system of linear equations using the `numpy.linalg` package.

In [8]:
np.linalg.solve(A, b)

array([ 1., -0., -1.,  2.])

## 2. Determinant
### 2.1 Compute the determinant of matrix $A$ using the `numpy.linalg` package:

$$ \begin{align}
  \textbf{A}  = \begin{bmatrix}
1 & 0 & -2\\
3 & 1 & -2\\
-5 & -1 & 9
\end{bmatrix}
  \end{align}
  $$

In [9]:
# Matrix
A = np.array([[1, 0, -2],
              [3, 1, -2],
              [-5, -1, 9]])

np.linalg.det(A)

3.000000000000001

### 2.2 Is the above matrix invertible? Why?

Answer here: Yes, above matrix is invertible beacuse determinant is not 0.

# 3. Matrix Inverse
### 3.1 Compute the inverse of non-singular matrix $B$ using row reduction
$$ \begin{align}
  \textbf{B}  = \begin{bmatrix}
1 & 2 & 1\\
4 & 4 & 5\\
6 & 7 & 7
\end{bmatrix}
  \end{align}
  $$

In [10]:
# Matrix
B = np.array([
    [1, 2, 1],
    [4, 4, 5],
    [6, 7, 7]
], dtype=float)

# Augmented Matrix
B_aug = np.hstack([B, np.eye(3)])
print("Augmented Matrix:")
print(B_aug)

Augmented Matrix:
[[1. 2. 1. 1. 0. 0.]
 [4. 4. 5. 0. 1. 0.]
 [6. 7. 7. 0. 0. 1.]]


In [11]:
# Row Operations
B_aug = MultiplyRow(B_aug, 0, 1/B_aug[0,0])
B_aug = AddRows(B_aug, 0, 1, -B_aug[1,0])
B_aug = AddRows(B_aug, 0, 2, -B_aug[2,0])
B_aug = MultiplyRow(B_aug, 1, 1/B_aug[1,1])
B_aug = AddRows(B_aug, 1, 2, -B_aug[2,1])
B_aug = MultiplyRow(B_aug, 2, 1/B_aug[2,2])
B_aug = AddRows(B_aug, 2, 1, -B_aug[1,2])
B_aug = AddRows(B_aug, 1, 0, -B_aug[0,1])
B_aug = AddRows(B_aug, 2, 0, -B_aug[0,2])
B_aug = AddRows(B_aug, 2, 1, -B_aug[1,2])
B_aug = AddRows(B_aug, 1, 0, -B_aug[0,1])
B_aug = MultiplyRow(B_aug, 2, -1)

B_inv = B_aug[:, 3:]
print("Inverse of B:")
print(B_inv)

Inverse of B:
[[-7. -7.  6.]
 [ 2.  1. -1.]
 [-4. -5.  4.]]


### 3.2 Compute the inverse matrix $B$ using the `numpy.linalg` package.

In [12]:
np.linalg.inv(B)

array([[-7., -7.,  6.],
       [ 2.,  1., -1.],
       [ 4.,  5., -4.]])